idade= 16
if idade < 5: #se idade menor que 5...
    preco= 0
elif idade < 18: #tambem se idade menor que 18...
    preco= 15
elif idade < 60: #tambem se idade menor que 60...
    preco= 30
else: # se não...
    preco= 15
    
print ("O preço da sua entrada está a R$" + str(preco))